select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != dcterms:title)
        filter(?iri != dcterms:source)
        filter(?iri != up:organism)
        filter(?iri != bp:pathwayComponent)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != owl:sameAs)
        filter(?iri != skos:related)
        filter(?iri != obo:RO_0000057)
        filter(?iri != rdf:type)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != bp:Pathway)
    }
    union
    {
        ?S obo:RO_0000057 ?iri .
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID'))
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/'))
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/'))
    }
    union
    {
        ?S bp:pathwayComponent ?iri .
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/'))
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/reaction/'))
    }
}
