select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != dcterms:title)
        filter(?iri != dcterms:source)
        filter(?iri != bao:BAO_0000209)
        filter(?iri != bao:BAO_0000540)
        filter(?iri != bao:BAO_0000210)
        filter(?iri != bao:BAO_0001067)
        filter(?iri != bao:BAO_0001094)
        filter(?iri != rdf:type)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != dcterms:identifier)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != bao:BAO_0000015)
    }
    union
    {
        ?iri dcterms:identifier ?O .
        filter(replace(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/AID', '') != str(?O))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(!strstarts(str(?iri), 'http://rdf.ebi.ac.uk/resource/chembl/assay/CHEMBL'))
        filter(!strstarts(str(?iri), 'http://rdf.ebi.ac.uk/resource/chembl/assay/drug_mech_'))
    }
}
