select distinct ?iri where
{
	{
	    ?S ?iri ?O .

	    filter(?S != <http://purl.obolibrary.org/obo/chebi.owl>)
	    filter(?S != <http://purl.obolibrary.org/obo/chebi#has_functional_parent>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#has_major_microspecies_at_pH_7_3>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#has_parent_hydride>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#is_conjugate_acid_of>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#is_enantiomer_of>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#is_substituent_group_from>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#is_tautomer_of>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#BRAND_NAME>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#INN>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#IUPAC_NAME>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#1_STAR>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#2_STAR>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi#3_STAR>)
        filter(?S != chebi:charge)
        filter(?S != chebi:formula)
        filter(?S != chebi:inchi)
        filter(?S != chebi:inchikey)
        filter(?S != chebi:mass)
        filter(?S != chebi:monoisotopicmass)
        filter(?S != chebi:smiles)
	    filter(?S != oboInOwl:SubsetProperty)
        filter(?S != oboInOwl:SynonymTypeProperty)
        filter(?S != oboInOwl:date)
        filter(?S != oboInOwl:default-namespace)
        filter(?S != oboInOwl:hasAlternativeId)
        filter(?S != oboInOwl:hasDbXref)
        filter(?S != oboInOwl:hasExactSynonym)
        filter(?S != oboInOwl:hasOBOFormatVersion)
        filter(?S != oboInOwl:hasOBONamespace)
        filter(?S != oboInOwl:hasRelatedSynonym)
        filter(?S != oboInOwl:hasSynonymType)
        filter(?S != oboInOwl:id)
        filter(?S != oboInOwl:inSubset)
        filter(?S != oboInOwl:is_cyclic)
        filter(?S != oboInOwl:is_transitive)
        filter(?S != oboInOwl:saved-by)
        filter(?S != oboInOwl:shorthand)
        filter(?S != oboInOwl:source)
        filter(?S != obo:IAO_0000115)
        filter(?S != obo:IAO_0000231)
        filter(?S != obo:IAO_0100001)
        filter(?S != obo:BFO_0000051)
        filter(?S != obo:RO_0000087)
        filter(?S != rdfs:comment)
        filter(?S != rdfs:label)
        filter(?S != owl:deprecated)
	    
        filter(?iri != rdf:type)
        filter(?iri !=  rdfs:subClassOf)
        filter(?iri != oboInOwl:inSubset)
        filter(?iri != obo:IAO_0100001)
        filter(?iri != obo:IAO_0000231)
        filter(?iri != owl:onProperty)
        filter(?iri != owl:someValuesFrom)
        filter(?iri != owl:annotatedProperty)
        filter(?iri != owl:annotatedSource)
        filter(?iri != owl:annotatedTarget)
        filter(?iri != oboInOwl:hasSynonymType)
        filter(?iri != oboInOwl:hasDbXref)
        filter(?iri != oboInOwl:source)       
        filter(?iri != oboInOwl:hasDbXref)
        filter(?iri != oboInOwl:hasRelatedSynonym)
        filter(?iri != oboInOwl:hasExactSynonym)
        filter(?iri != chebi:formula)
        filter(?iri != chebi:mass)
        filter(?iri != chebi:monoisotopicmass)
        filter(?iri != oboInOwl:hasAlternativeId)
        filter(?iri != rdfs:label)
        filter(?iri != oboInOwl:id)
        filter(?iri != oboInOwl:hasOBONamespace)
        filter(?iri != chebi:charge)
        filter(?iri != chebi:smiles)
        filter(?iri != chebi:inchikey)
        filter(?iri != chebi:inchi)
        filter(?iri != obo:IAO_0000115)
        filter(?iri != owl:deprecated)
	}
}
