select distinct ?iri where
{
	{
	    ?S ?iri ?O .
	    filter(?S != <http://purl.obolibrary.org/obo/chebi.owl>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/BRAND_NAME>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/INN>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/IUPAC_NAME>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/1_STAR>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/2_STAR>)
        filter(?S != <http://purl.obolibrary.org/obo/chebi/3_STAR>)
        filter(?S != chemrof:charge)
        filter(?S != chemrof:generalized_empirical_formula)
        filter(?S != chemrof:inchi_key_string)
        filter(?S != chemrof:inchi_string)
        filter(?S != chemrof:mass)
        filter(?S != chemrof:monoisotopic_mass)
        filter(?S != chemrof:smiles_string)
        filter(?S != chemrof:wurcs_representation)
	    filter(?S != oboInOwl:SubsetProperty)
        filter(?S != oboInOwl:SynonymTypeProperty)
        filter(?S != oboInOwl:date)
        filter(?S != oboInOwl:default-namespace)
        filter(?S != oboInOwl:hasAlternativeId)
        filter(?S != oboInOwl:hasDbXref)
        filter(?S != oboInOwl:hasExactSynonym)
        filter(?S != oboInOwl:hasOBOFormatVersion)
        filter(?S != oboInOwl:hasOBONamespace)
        filter(?S != oboInOwl:hasRelatedSynonym)
        filter(?S != oboInOwl:hasSynonymType)
        filter(?S != oboInOwl:id)
        filter(?S != oboInOwl:inSubset)
        filter(?S != oboInOwl:is_cyclic)
        filter(?S != oboInOwl:is_transitive)
        filter(?S != oboInOwl:saved-by)
        filter(?S != oboInOwl:shorthand)
        filter(?S != oboInOwl:source)
        filter(?S != obo:IAO_0000115)
        filter(?S != obo:IAO_0000231)
        filter(?S != obo:IAO_0100001)
        filter(?S != obo:BFO_0000051)
        filter(?S != obo:RO_0000087)
        filter(?S != obo:RO_0018033)
        filter(?S != obo:RO_0018034)
        filter(?S != obo:RO_0018036)
        filter(?S != obo:RO_0018037)
        filter(?S != obo:RO_0018038)
        filter(?S != obo:RO_0018039)
        filter(?S != obo:RO_0018040)
        filter(?S != rdfs:comment)
        filter(?S != rdfs:label)
        filter(?S != owl:deprecated)

        filter(?iri != rdf:type)
        filter(?iri != rdfs:subClassOf)
        filter(?iri != oboInOwl:inSubset)
        filter(?iri != obo:IAO_0100001)
        filter(?iri != obo:IAO_0000231)
        filter(?iri != owl:onProperty)
        filter(?iri != owl:someValuesFrom)
        filter(?iri != owl:annotatedProperty)
        filter(?iri != owl:annotatedSource)
        filter(?iri != owl:annotatedTarget)
        filter(?iri != oboInOwl:hasSynonymType)
        filter(?iri != oboInOwl:hasDbXref)
        filter(?iri != oboInOwl:source)       
        filter(?iri != oboInOwl:hasDbXref)
        filter(?iri != oboInOwl:hasRelatedSynonym)
        filter(?iri != oboInOwl:hasExactSynonym)
        filter(?iri != oboInOwl:hasAlternativeId)
        filter(?iri != chemrof:charge)
        filter(?iri != chemrof:generalized_empirical_formula)
        filter(?iri != chemrof:inchi_key_string)
        filter(?iri != chemrof:inchi_string)
        filter(?iri != chemrof:mass)
        filter(?iri != chemrof:monoisotopic_mass)
        filter(?iri != chemrof:smiles_string)
        filter(?iri != chemrof:wurcs_representation)
        filter(?iri != rdfs:label)
        filter(?iri != oboInOwl:id)
        filter(?iri != oboInOwl:hasOBONamespace)
        filter(?iri != obo:IAO_0000115)
        filter(?iri != owl:deprecated)
	}
}
