select distinct ?iri where
{
	{
	    ?S ?iri ?O .
	    filter(?iri != <http://purl.org/pav/importedFrom>)
	    filter(?iri != skos:broader)
	    filter(?iri != skos:inScheme)
	    filter(?iri != skos:prefLabel)
	    filter(?iri != rdf:type)
	}
    union
	{
	    ?S rdf:type ?iri .
	    filter(?iri != skos:ConceptScheme)
	    filter(?iri != skos:Concept)
	    filter(?iri != skos:concept)
	}
    union
	{
	    ?S <http://purl.org/pav/importedFrom> ?iri
	    filter(?iri != source:WHO)
	}
    union
	{
	    ?iri rdf:type skos:ConceptScheme
	    filter(?iri != concept:ATC)
	    filter(?iri != concept:SubstanceCategorization)
	}
}
