create index documents__chembl_id on chembl.documents(chembl_id);
create index documents__journal on chembl.documents(journal);
create index documents__type on chembl.documents(type);
create index documents__title on chembl.documents(title);
create index documents__year on chembl.documents(year);
create index documents__volume on chembl.documents(volume);
create index documents__issue on chembl.documents(issue);
create index documents__first_page on chembl.documents(first_page);
create index documents__last_page on chembl.documents(last_page);
create index documents__doi on chembl.documents(doi);
create index documents__pubmed on chembl.documents(pubmed);
grant select on chembl.documents to sparql;
