create index document_bases__chembl_id on chembl.document_bases(chembl_id);
create index document_bases__journal on chembl.document_bases(journal);
create index document_bases__type on chembl.document_bases(type);
create index document_bases__title on chembl.document_bases(title);
create index document_bases__year on chembl.document_bases(year);
create index document_bases__volume on chembl.document_bases(volume);
create index document_bases__issue on chembl.document_bases(issue);
create index document_bases__first_page on chembl.document_bases(first_page);
create index document_bases__last_page on chembl.document_bases(last_page);
create index document_bases__doi on chembl.document_bases(doi);
create index document_bases__pubmed on chembl.document_bases(pubmed);
grant select on chembl.document_bases to sparql;
