select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != skos:prefLabel)
        filter(?iri != skos:altLabel)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != up:organism)
        filter(?iri != obo:BFO_0000050)
        filter(?iri != obo:RO_0001000)
	}
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != obo:CLO_0000031)
        filter(?iri != sio:SIO_010054)
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/CL_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/CLO_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/BTO_'))
        filter(!strstarts(str(?iri), 'http://www.ebi.ac.uk/efo/EFO_'))
        filter(!strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(!strstarts(str(?iri), 'http://id.nlm.nih.gov/mesh/'))
        filter(!strstarts(str(?iri), 'https://www.cancerrxgene.org/translation/CellLine/'))
        filter(!strstarts(str(?iri), 'https://depmap.org/portal/cell_line/ACH-'))
        filter(!strstarts(str(?iri), 'https://cellmodelpassports.sanger.ac.uk/passports/SIDM'))
        filter(!strstarts(str(?iri), 'https://cancer.sanger.ac.uk/cell_lines/sample/overview?id='))
        filter(!strstarts(str(?iri), 'http://identifiers.org/ncit:C'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/CL:'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/lincs.cell:LCL-'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/efo:'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/BTO:'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/CLO:'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/wikidata:Q'))
        filter(!strstarts(str(?iri), 'http://rdf.ebi.ac.uk/resource/chembl/cell_line/CHEMBL'))
        filter(!strstarts(str(?iri), 'http://identifiers.org/cellosaurus:CVCL_'))
        filter(!strstarts(str(?iri), 'https://lincs.hms.harvard.edu/db/cells/'))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        bind (replace(str(?iri), 'http://identifiers.org/mesh:', '') as ?match)
        
        minus
        {
            ?S rdfs:seeAlso ?iri2 .
            filter(strstarts(str(?iri2), 'http://id.nlm.nih.gov/mesh/'))
            bind (replace(str(?iri2), 'http://id.nlm.nih.gov/mesh/', '') as ?match)
        }
    }
}
