select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != vcard:given-name)
        filter(?iri != vcard:family-name)
        filter(?iri != vcard:fn)
        filter(?iri != vcard:organization-name)
        filter(?iri != vcard:hasUID)
        filter(?iri != dcterms:source)
	}
    union
	{
	    ?S dcterms:source ?iri
	    filter(?iri != <https://orcid.org>)
	}
}
