select distinct ?iri ?title where
{
    {
        ?iri rdf:type dcterms:Dataset .

        optional { ?iri dcterms:title ?title }
    }
    union
    {
        values (?iri ?title) {(source:WHO 'WHO')}

        filter not exists { source:WHO rdf:type dcterms:Dataset }  
    }
}
