select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(! strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/MD5_'))
        filter(?iri != skos:altLabel)
        filter(?iri != skos:prefLabel)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != rdf:type)
        filter(?iri != obo:RO_0000056)
        filter(?iri != obo:RO_0000085)
        filter(?iri != obo:RO_0001025)
        filter(?iri != bao:BAO_0002870)
        filter(?iri != up:organism)
        filter(?iri != sio:SIO_000558)
        filter(?iri != dcterms:identifier)
    }
    union
    {
        ?S ?iri ?O .
        filter(strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/MD5_'))
        filter(?iri != rdf:type)
        filter(?iri != sio:SIO_000300)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(! strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/MD5_'))
        filter(?iri != sio:SIO_010035)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/MD5_'))
        filter(?iri != sio:SIO_001383)
    }
    union
    {
        ?iri dcterms:identifier ?O .
        filter(replace(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/GID', '') != str(?O))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(! strstarts(str(?iri), 'http://rdf.ebi.ac.uk/resource/ensembl/'))
        filter(! strstarts(str(?iri), 'http://id.nlm.nih.gov/mesh/'))
        filter(! strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(! strstarts(str(?iri), 'https://enzyme.expasy.org/EC/'))
        filter(! strstarts(str(?iri), 'https://medlineplus.gov/genetics/gene/'))
        filter(! strstarts(str(?iri), 'https://www.alliancegenome.org/gene/'))
        filter(! strstarts(str(?iri), 'http://www.wormbase.org/db/gene/gene?name=WBGene'))
        filter(! strstarts(str(?iri), 'https://pharos.nih.gov/targets/'))
        filter(! strstarts(str(?iri), 'https://platform.opentargets.org/target/ENSG'))
        filter(! strstarts(str(?iri), 'https://search.thegencc.org/genes/HGNC:'))
        filter(! strstarts(str(?iri), 'https://www.veupathdb.org/gene/'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/kegg.genes:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/bgee.gene:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ensembl:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/pombase:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/zfin:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ctd.gene:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/mim:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/hgnc:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/rgd:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/MGI:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ncit:C'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/pharmgkb.gene:PA'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/sgd:S'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/xenbase:XB-GENE-'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/xenbase:XB-GENEPAGE-'))
        filter(! strstarts(str(?iri), 'http://purl.uniprot.org/enzyme/'))
        filter(! strstarts(str(?iri), 'http://glycosmos.org/glycogene/'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/fb:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ncbigene:'))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/ensembl:'))
        bind (replace(str(?iri), 'http://identifiers.org/ensembl:', '') as ?match)
        
        minus
        {
            ?S rdfs:seeAlso ?iri2 .
            filter(strstarts(str(?iri2), 'http://rdf.ebi.ac.uk/resource/ensembl/'))
            bind (replace(str(?iri2), 'http://rdf.ebi.ac.uk/resource/ensembl/', '') as ?match)
        }
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        bind (replace(str(?iri), 'http://identifiers.org/mesh:', '') as ?match)
        
        minus
        {
            ?S rdfs:seeAlso ?iri2 .
            filter(strstarts(str(?iri2), 'http://id.nlm.nih.gov/mesh/'))
            bind (replace(str(?iri2), 'http://id.nlm.nih.gov/mesh/', '') as ?match)
        }
    }
}
