select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != frapo:hasGrantNumber)
        filter(?iri != frapo:hasFundingAgency)
	}
    union
	{
	    ?S rdf:type ?iri .
	    filter(?iri != frapo:Grant)
	}
}
