select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != meshv:altLabel)
        filter(?iri != meshv:previousIndexing)
        filter(?iri != meshv:source)
        filter(?iri != meshv:thesaurusID)
        filter(?iri != rdfs:label)
        filter(?iri != meshv:abbreviation)
        filter(?iri != meshv:annotation)
        filter(?iri != meshv:casn1_label)
        filter(?iri != meshv:considerAlso)
        filter(?iri != meshv:entryVersion)
        filter(?iri != meshv:historyNote)
        filter(?iri != meshv:lastActiveYear)
        filter(?iri != meshv:lexicalTag)
        filter(?iri != meshv:note)
        filter(?iri != meshv:onlineNote)
        filter(?iri != meshv:prefLabel)
        filter(?iri != meshv:publicMeSHNote)
        filter(?iri != meshv:scopeNote)
        filter(?iri != meshv:sortVersion)
        filter(?iri != meshv:relatedRegistryNumber)
        filter(?iri != meshv:identifier)
        filter(?iri != meshv:nlmClassificationNumber)
        filter(?iri != meshv:registryNumber)
        filter(?iri != meshv:active)
        filter(?iri != meshv:frequency)
        filter(?iri != meshv:dateCreated)
        filter(?iri != meshv:dateRevised)
        filter(?iri != meshv:dateEstablished)
        filter(?iri != meshv:allowableQualifier)
        filter(?iri != meshv:broaderConcept)
        filter(?iri != meshv:broaderDescriptor)
        filter(?iri != meshv:broaderQualifier)
        filter(?iri != meshv:concept)
        filter(?iri != meshv:indexerConsiderAlso)
        filter(?iri != meshv:mappedTo)
        filter(?iri != meshv:narrowerConcept)
        filter(?iri != meshv:pharmacologicalAction)
        filter(?iri != meshv:preferredMappedTo)
        filter(?iri != meshv:relatedConcept)
        filter(?iri != meshv:seeAlso)
        filter(?iri != meshv:term)
        filter(?iri != meshv:treeNumber)
        filter(?iri != meshv:hasDescriptor)
        filter(?iri != meshv:hasQualifier)
        filter(?iri != meshv:parentTreeNumber)
        filter(?iri != meshv:preferredConcept)
        filter(?iri != meshv:preferredTerm)
        filter(?iri != meshv:useInstead)
	}
}
