select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(! strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/EC_'))
        filter(?iri != obo:RO_0002180)
        filter(?iri != up:encodedBy)
        filter(?iri != up:organism)
        filter(?iri != up:enzyme)
        filter(?iri != vocab:hasSimilarProtein)
        filter(?iri != pdbo40:link_to_pdb)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != rdf:type)
        filter(?iri != skos:prefLabel)
        filter(?iri != skos:altLabel)
        filter(?iri != bao:BAO_0002817)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != dcterms:identifier)
    }
    union
    {
        ?S ?iri ?O .
        filter(strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/EC_'))
        filter(?iri != rdf:type)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != rdfs:subClassOf)
        filter(?iri != skos:prefLabel)
        filter(?iri != skos:altLabel)
    }
    union
    {
        ?iri dcterms:identifier ?O .
        filter(replace(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/ACC', '') != str(?O))
    }
    union
    {
        ?S obo:RO_0002180 ?iri .
        filter(! strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/conserveddomain/PSSMID'))
        filter(! strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/'))
        filter(! strstarts(str(?iri), 'https://pfam.xfam.org/family/PF'))
        filter(! strstarts(str(?iri), 'https://www.ebi.ac.uk/interpro/entry/InterPro/IPR'))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(! strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/EC_'))
        filter(! strstarts(str(?iri), 'http://purl.uniprot.org/uniprot/'))
        filter(! strstarts(str(?iri), 'http://id.nlm.nih.gov/mesh/'))
        filter(! strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(! strstarts(str(?iri), 'https://www.drugbank.ca/bio_entities/BE'))
        filter(! strstarts(str(?iri), 'https://alphafold.ebi.ac.uk/entry/'))
        filter(! strstarts(str(?iri), 'https://pharos.nih.gov/targets/'))
        filter(! strstarts(str(?iri), 'https://platform.opentargets.org/target/ENSG'))
        filter(! strstarts(str(?iri), 'https://wormbase.org/db/seq/protein?name='))
        filter(! strstarts(str(?iri), 'https://www.brenda-enzymes.org/enzyme.php?ecno='))
        filter(! strstarts(str(?iri), 'https://www.ebi.ac.uk/intact/search?query='))
        filter(! strstarts(str(?iri), 'https://www.ebi.ac.uk/interpro/protein/reviewed/'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/nextprot:NX_'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/uniprot:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/refseq:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/chembl:CHEMBL'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/iuphar.receptor:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ncit:C'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/hpa:ENSG'))
        filter(! strstarts(str(?iri), 'https://glygen.org/protein/'))
        filter(! strstarts(str(?iri), 'https://glycosmos.org/glycoproteins/'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/PR:'))
        filter(! strstarts(str(?iri), 'http://identifiers.org/ncbiprotein:'))
        filter(! strstarts(str(?iri), 'http://purl.obolibrary.org/obo/PR_'))
        filter(! strstarts(str(?iri), 'http://rdf.ebi.ac.uk/resource/chembl/target/CHEMBL'))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/EC_'))
        filter(replace(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/EC_', '') != replace(str(?iri), 'http://purl.uniprot.org/enzyme/', ''))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/ncbiprotein:'))
        filter(replace(str(?S), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/ACC', '') != replace(str(?iri), 'http://identifiers.org/ncbiprotein:', ''))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/uniprot:'))
        bind (replace(str(?iri), 'http://identifiers.org/uniprot:', '') as ?match)
        
        minus
        {
            ?S rdfs:seeAlso ?iri2 .
            filter(strstarts(str(?iri2), 'http://purl.uniprot.org/uniprot/'))
            bind (replace(str(?iri2), 'http://purl.uniprot.org/uniprot/', '') as ?match)
        }
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(strstarts(str(?iri), 'http://identifiers.org/mesh:'))
        bind (replace(str(?iri), 'http://identifiers.org/mesh:', '') as ?match)
        
        minus
        {
            ?S rdfs:seeAlso ?iri2 .
            filter(strstarts(str(?iri2), 'http://id.nlm.nih.gov/mesh/'))
            bind (replace(str(?iri2), 'http://id.nlm.nih.gov/mesh/', '') as ?match)
        }
    }
}
