select distinct ?class where
{
    {
        select distinct ?class where
        {    
            {
                ?class rdf:type owl:Class
            }
            union
            {
                ?class rdfs:subClassOf ?S
            }
            union
            {
                ?C rdfs:subClassOf ?class
            }
            union
            {
                ?S rdfs:domain ?class
            }
            union
            {
                ?S rdfs:range ?class
            }
        }
    }
    
    filter(!isblank(?class))
    filter(?class != owl:Thing)
    filter(?class != rdfs:Resource)

    minus
    {
        ?class rdfs:subClassOf []
    }
}
