select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != dcterms:abstract)
        filter(?iri != dcterms:title)
        filter(?iri != rdf:type)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != obo:SO_0000417)
    }
}
