select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != skos:prefLabel)
        filter(?iri != skos:altLabel)
        filter(?iri != skos:closeMatch)
        filter(?iri != skos:relatedMatch)
	}
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != obo:DOID_4)
        filter(?iri != obo:MONDO_0000001)
    }
    union
    {
        ?S skos:relatedMatch ?iri .
        filter(!strstarts(str(?iri), 'https://uts.nlm.nih.gov/uts/umls/concept/C'))
        filter(!strstarts(str(?iri), 'https://uts.nlm.nih.gov/uts/umls/concept/CN'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/MONDO_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/DOID_0'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/DOID_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/HP_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/'))
        filter(!strstarts(str(?iri), 'https://omim.org/entry/'))
        filter(!strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(!strstarts(str(?iri), 'https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert='))
        filter(!strstarts(str(?iri), 'https://www.ncbi.nlm.nih.gov/medgen/C'))
        filter(!strstarts(str(?iri), 'https://www.ncbi.nlm.nih.gov/medgen/CN'))
        filter(!strstarts(str(?iri), 'https://rarediseases.info.nih.gov/diseases/'))
        filter(!strstarts(str(?iri), 'https://www.guidetopharmacology.org/GRAC/DiseaseDisplayForward?diseaseId='))
    }
    union
    {
        ?S skos:closeMatch ?iri .
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/MONDO_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/DOID_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/HP_'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/'))
        filter(!strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(!strstarts(str(?iri), 'https://uts.nlm.nih.gov/uts/umls/concept/C'))
        filter(!strstarts(str(?iri), 'https://uts.nlm.nih.gov/uts/umls/concept/CN'))
        filter(!strstarts(str(?iri), 'https://www.ncbi.nlm.nih.gov/medgen/C'))
        filter(!strstarts(str(?iri), 'https://www.ncbi.nlm.nih.gov/medgen/CN'))
        filter(!strstarts(str(?iri), 'https://omim.org/entry/'))
        filter(!strstarts(str(?iri), 'https://rarediseases.info.nih.gov/diseases/'))
        filter(!strstarts(str(?iri), 'https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert='))
        filter(!strstarts(str(?iri), 'https://www.guidetopharmacology.org/GRAC/DiseaseDisplayForward?diseaseId='))
        filter(!strstarts(str(?iri), 'http://id.nlm.nih.gov/mesh/'))
    }
}
