select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != obo:has-role)
    }
    union
    {
        ?S rdf:type ?iri .
    }
    union
    {
        ?S obo:has-role ?iri
        filter(?iri != vocab:FDAApprovedDrugs)
    }
}
