select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != vocab:is_active_ingredient_of)
    }
    union
    {
        ?S rdf:type ?iri .
    }
    union
    {
        ?S vocab:is_active_ingredient_of ?iri .
        filter(! strstarts(str(?iri), "http://purl.bioontology.org/ontology/SNOMEDCT/"))
        filter(! strstarts(str(?iri), "http://purl.bioontology.org/ontology/NDFRT/N"))
    }
}
