select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != rdf:type)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(! strstarts(str(?iri), "http://purl.obolibrary.org/obo/CHEBI_"))
        filter(! strstarts(str(?iri), "http://purl.bioontology.org/ontology/SNOMEDCT/"))
        filter(! strstarts(str(?iri), "http://purl.bioontology.org/ontology/NDFRT/N"))
        filter(! strstarts(str(?iri), "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C"))
        filter(?iri != bp:SmallMolecule)
    }
}
