prefix rdf:             <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:            <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:             <http://www.w3.org/2002/07/owl#>
prefix xsd:             <http://www.w3.org/2001/XMLSchema#>

prefix compound:        <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
prefix substance:       <http://rdf.ncbi.nlm.nih.gov/pubchem/substance/>
prefix descriptor:      <http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/>
prefix synonym:         <http://rdf.ncbi.nlm.nih.gov/pubchem/synonym/>
prefix inchikey:        <http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey/>
prefix bioassay:        <http://rdf.ncbi.nlm.nih.gov/pubchem/bioassay/>
prefix measuregroup:    <http://rdf.ncbi.nlm.nih.gov/pubchem/measuregroup/>
prefix endpoint:        <http://rdf.ncbi.nlm.nih.gov/pubchem/endpoint/>
prefix reference:       <http://rdf.ncbi.nlm.nih.gov/pubchem/reference/>
prefix protein:         <http://rdf.ncbi.nlm.nih.gov/pubchem/protein/>
prefix conserveddomain: <http://rdf.ncbi.nlm.nih.gov/pubchem/conserveddomain/>
prefix gene:            <http://rdf.ncbi.nlm.nih.gov/pubchem/gene/>
prefix biosystem:       <http://rdf.ncbi.nlm.nih.gov/pubchem/biosystem/>
prefix source:          <http://rdf.ncbi.nlm.nih.gov/pubchem/source/>
prefix concept:         <http://rdf.ncbi.nlm.nih.gov/pubchem/concept/>
prefix vocab:           <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>
prefix obo:             <http://purl.obolibrary.org/obo/>
prefix sio:             <http://semanticscience.org/resource/>
prefix skos:            <http://www.w3.org/2004/02/skos/core#>
prefix bao:             <http://www.bioassayontology.org/bao#>
prefix bp:              <http://www.biopax.org/release/biopax-level3.owl#>
prefix ndfrt:           <http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#>
prefix ncit:            <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
prefix wikidata:        <http://www.wikidata.org/entity/>
prefix ops:             <http://www.openphacts.org/units/>
prefix cito:            <http://purl.org/spar/cito/>
prefix fabio:           <http://purl.org/spar/fabio/>
prefix uniprot:         <http://purl.uniprot.org/uniprot/>
prefix pdbo:            <http://rdf.wwpdb.org/schema/pdbx-v40.owl#>
prefix pdbr:            <http://rdf.wwpdb.org/pdb/>
prefix taxonomy:        <http://identifiers.org/taxonomy/>
prefix reactome:        <http://identifiers.org/reactome/>
prefix chembl:          <http://rdf.ebi.ac.uk/resource/chembl/molecule/>
prefix chemblchembl:    <http://linkedchemistry.info/chembl/chemblid/>
prefix foaf:            <http://xmlns.com/foaf/0.1/>
prefix void:            <http://rdfs.org/ns/void#>
prefix dcterms:         <http://purl.org/dc/terms/>
prefix ensembl:         <http://rdf.ebi.ac.uk/resource/ensembl/>

prefix meshv:           <http://id.nlm.nih.gov/mesh/vocab#>
prefix mesh:            <http://id.nlm.nih.gov/mesh/>

prefix chebi:           <http://purl.obolibrary.org/obo/chebi/>
prefix oboInOwl:        <http://www.geneontology.org/formats/oboInOwl#>

prefix cco:             <http://rdf.ebi.ac.uk/terms/chembl#>
prefix bibo:            <http://purl.org/ontology/bibo/>
