select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != owl:sameAs)
        filter(?iri != skos:prefLabel)
        filter(?iri != skos:altLabel)
        filter(?iri != skos:closeMatch)
        filter(?iri != cito:isDiscussedBy)
	}
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != sio:SIO_001262)
    }
    union
    {
        ?S skos:closeMatch ?iri .
        filter(!strstarts(str(?iri), 'http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C'))
        filter(!strstarts(str(?iri), 'http://purl.obolibrary.org/obo/BTO_'))
        filter(!strstarts(str(?iri), 'http://www.ebi.ac.uk/efo/EFO_'))
        filter(!strstarts(str(?iri), 'https://www.ebi.ac.uk/chembl/tissue_report_card/CHEMBL'))
        filter(!strstarts(str(?iri), 'https://www.nextprot.org/term/TS-'))
        filter(!strstarts(str(?iri), 'http://id.nlm.nih.gov/mesh/'))
    }
}
