alter table chembl_tmp.activities drop column doc_id;
alter table chembl_tmp.activities drop column record_id;
alter table chembl_tmp.activities drop column molregno;
alter table chembl_tmp.activities drop column standard_flag;
alter table chembl_tmp.activities drop column bao_endpoint;
alter table chembl_tmp.activities drop column uo_units;
alter table chembl_tmp.activities drop column qudt_units;
alter table chembl_tmp.activities drop column toid;
alter table chembl_tmp.activities drop column upper_value;
alter table chembl_tmp.activities drop column standard_upper_value;
alter table chembl_tmp.activities drop column src_id;
alter table chembl_tmp.activities drop column text_value;
alter table chembl_tmp.activities drop column standard_text_value;

alter table chembl_tmp.activities add primary key (id);
create index activities__assay_id on chembl_tmp.activities(assay_id);
create index activities__standard_relation on chembl_tmp.activities(standard_relation);
create index activities__standard_value on chembl_tmp.activities(standard_value);
create index activities__standard_units on chembl_tmp.activities(standard_units);
create index activities__standard_type on chembl_tmp.activities(standard_type);
create index activities__activity_comment on chembl_tmp.activities(activity_comment);
create index activities__data_validity_comment on chembl_tmp.activities(data_validity_comment);
create index activities__potential_duplicate on chembl_tmp.activities(potential_duplicate);
create index activities__pchembl_value on chembl_tmp.activities(pchembl_value);
create index activities__type on chembl_tmp.activities(type);
create index activities__relation on chembl_tmp.activities(relation);
create index activities__value on chembl_tmp.activities(value);
create index activities__document_id on chembl_tmp.activities(document_id);
create index activities__molecule_id on chembl_tmp.activities(molecule_id);
create index activities__qudt_id on chembl_tmp.activities(qudt_id);
create index activities__uo_unit_id on chembl_tmp.activities(uo_unit_id);
create index activities__bao_endpoint_id on chembl_tmp.activities(bao_endpoint_id);
create index activities__chembl_id on chembl_tmp.activities(chembl_id);
grant select on chembl_tmp.activities to sparql;
