alter table chembl.activities drop column doc_id;
alter table chembl.activities drop column record_id;
alter table chembl.activities drop column molregno;
alter table chembl.activities drop column standard_flag;
alter table chembl.activities drop column bao_endpoint;
alter table chembl.activities drop column uo_units;
alter table chembl.activities drop column qudt_units;
alter table chembl.activities drop column toid;
alter table chembl.activities drop column upper_value;
alter table chembl.activities drop column standard_upper_value;
alter table chembl.activities drop column src_id;
alter table chembl.activities drop column text_value;
alter table chembl.activities drop column standard_text_value;

alter table chembl.activities add primary key (id);
create index activities__assay_id on chembl.activities(assay_id);
create index activities__standard_relation on chembl.activities(standard_relation);
create index activities__standard_value on chembl.activities(standard_value);
create index activities__standard_units on chembl.activities(standard_units);
create index activities__standard_type on chembl.activities(standard_type);
create index activities__activity_comment on chembl.activities(activity_comment);
create index activities__data_validity_comment on chembl.activities(data_validity_comment);
create index activities__potential_duplicate on chembl.activities(potential_duplicate);
create index activities__pchembl_value on chembl.activities(pchembl_value);
create index activities__type on chembl.activities(type);
create index activities__relation on chembl.activities(relation);
create index activities__value on chembl.activities(value);
create index activities__document_id on chembl.activities(document_id);
create index activities__molecule_id on chembl.activities(molecule_id);
create index activities__qudt_id on chembl.activities(qudt_id);
create index activities__uo_unit_id on chembl.activities(uo_unit_id);
create index activities__bao_endpoint_id on chembl.activities(bao_endpoint_id);
create index activities__chembl_id on chembl.activities(chembl_id);
grant select on chembl.activities to sparql;
