select distinct ?iri where
{
    {
        ?S ?iri ?O .
        filter(?iri != dcterms:title)
        filter(?iri != dcterms:source)
        filter(?iri != up:organism)
        filter(?iri != bp:pathwayComponent)
        filter(?iri != cito:isDiscussedBy)
        filter(?iri != rdfs:seeAlso)
        filter(?iri != skos:related)
        filter(?iri != obo:RO_0000057)
        filter(?iri != rdf:type)
    }
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != bp:Pathway)
    }
    union
    {
        ?S obo:RO_0000057 ?iri .
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID'))
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/protein/'))
        filter(!strstarts(str(?iri), 'http://rdf.ncbi.nlm.nih.gov/pubchem/gene/'))
    }
    union
    {
        ?S rdfs:seeAlso ?iri .
        filter(!strstarts(str(?iri), ''))
        filter(!strstarts(str(?match), 'http://pathbank.org/view/'))
        filter(!strstarts(str(?match), 'https://pmn.plantcyc.org/pathway?'))
        filter(!strstarts(str(?match), 'https://plantreactome.gramene.org/content/detail/'))
        filter(!strstarts(str(?match), 'https://fairdomhub.org/models/'))
        filter(!strstarts(str(?match), 'https://www.lipidmaps.org/data/IntegratedPathwaysData/SetupIntegratedPathways.pl?imgsize=730&Mode=BMDMATPS11&DataType='))
        filter(!strstarts(str(?match), 'http://identifiers.org/pid.pathway:'))
        filter(!strstarts(str(?match), 'http://identifiers.org/wikipathways:'))
        filter(!strstarts(str(?match), 'http://identifiers.org/reactome:'))
        filter(!strstarts(str(?match), 'http://identifiers.org/panther.pathway:'))
        filter(!strstarts(str(?match), 'http://identifiers.org/pharmgkb.pathways:'))
        filter(!strstarts(str(?match), 'http://identifiers.org/biocyc:'))
    }
}
