drop table descriptor_compound_preferred_iupac_names;
drop table descriptor_compound_iupac_inchis;
drop table descriptor_compound_canonical_smileses;
drop table descriptor_compound_isomeric_smileses;
drop table descriptor_compound_molecular_formulas;
drop table descriptor_compound_bases;
