drop function hydrogen_bond_acceptor_count(id in integer);
drop function hydrogen_bond_acceptor_count_inverse(iri in varchar);
drop function tautomer_count(id in integer);
drop function tautomer_count_inverse(iri in varchar);
drop function defined_atom_stereo_count(id in integer);
drop function defined_atom_stereo_count_inverse(iri in varchar);
drop function defined_bond_stereo_count(id in integer);
drop function defined_bond_stereo_count_inverse(iri in varchar);
drop function undefined_bond_stereo_count(id in integer);
drop function undefined_bond_stereo_count_inverse(iri in varchar);
drop function isotope_atom_count(id in integer);
drop function isotope_atom_count_inverse(iri in varchar);
drop function covalent_unit_count(id in integer);
drop function covalent_unit_count_inverse(iri in varchar);
drop function hydrogen_bond_donor_count(id in integer);
drop function hydrogen_bond_donor_count_inverse(iri in varchar);
drop function non_hydrogen_atom_count(id in integer);
drop function non_hydrogen_atom_count_inverse(iri in varchar);
drop function rotatable_bond_count(id in integer);
drop function rotatable_bond_count_inverse(iri in varchar);
drop function undefined_atom_stereo_count(id in integer);
drop function undefined_atom_stereo_count_inverse(iri in varchar);
drop function total_formal_charge(id in integer);
drop function total_formal_charge_inverse(iri in varchar);
drop function structure_complexity(id in integer);
drop function structure_complexity_inverse(iri in varchar);
drop function mono_isotopic_weight(id in integer);
drop function mono_isotopic_weight_inverse(iri in varchar);
drop function xlogp3_aa(id in integer);
drop function xlogp3_aa_inverse(iri in varchar);
drop function exact_mass(id in integer);
drop function exact_mass_inverse(iri in varchar);
drop function molecular_weight(id in integer);
drop function molecular_weight_inverse(iri in varchar);
drop function tpsa(id in integer);
drop function tpsa_inverse(iri in varchar);
drop function molecular_formula(id in integer);
drop function molecular_formula_inverse(iri in varchar);
drop function isomeric_smiles(id in integer);
drop function isomeric_smiles_inverse(iri in varchar);
drop function canonical_smiles(id in integer);
drop function canonical_smiles_inverse(iri in varchar);
drop function iupac_inchi(id in integer);
drop function iupac_inchi_inverse(iri in varchar);
drop function preferred_iupac_name(id in integer);
drop function preferred_iupac_name_inverse(iri in varchar);

--------------------------------------------------------------------------------

drop table descriptor_compound_preferred_iupac_names;
drop table descriptor_compound_iupac_inchis;
drop table descriptor_compound_canonical_smileses;
drop table descriptor_compound_isomeric_smileses;
drop table descriptor_compound_molecular_formulas;
drop table descriptor_compound_bases;
