select distinct ?iri where
{
	{
	    ?S ?iri ?O .
        filter(?iri != rdf:type)
        filter(?iri != dcterms:creator)
        filter(?iri != dcterms:title)
        filter(?iri != dcterms:publisher)
        filter(?iri != dcterms:date)
        filter(?iri != prism:location)
        filter(?iri != prism:isbn)
        filter(?iri != prism:subtitle)
        filter(?iri != skos:exactMatch)
	}
    union
    {
        ?S rdf:type ?iri .
        filter(?iri != fabio:Book)
    }
    union
    {
        ?S skos:exactMatch ?iri .
        filter(replace(str(?S), "http://rdf.ncbi.nlm.nih.gov/pubchem/book/", "") != replace(str(?iri), "https://www.ncbi.nlm.nih.gov/books/", ""))
    }
}
